document.write(2+3*2);
document.write("<br>")
document.write((2+3)*2);
document.write("<br>")
document.write(10/2+5);
document.write("<br>")
document.write(10/2*5);
document.write("<br>")
document.write(2**2);
document.write("<br>")
document.write(2**3);